spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.156.68.221:3306/ssm?characterEncoding=utf8&useSSL=false
    username: ssm
    password: 3344520..hhy
  data:
    redis:
      # 基本连接配置
      host: 8.156.68.221
      port: 16379
      password: 3344520..hhy
      timeout: 20000
      lettuce:
        pool:
          enabled: true
          max-active: 200
          max-idle: 50
          min-idle: 20
          max-wait: 1000
security:
  ignore:
    urls:
      - /auth/login
      - /auth/code